[package]
name = "thruster-server"
version = "0.1.0"
authors = ["Pete Mertz <peter.s.mertz@gmail.com>"]
description = "A middleware based http async web server."
readme = "README.md"
license = "MIT"
documentation = "https://thruster.github.com"
homepage = "https://thruster.github.com"
repository = "https://github.com/trezm/thruster"
edition = "2018"

[dependencies]
futures-legacy = { version = "0.1.23", package = "futures" }
futures-preview = "0.3.0-alpha.13"
net2 = "0.2"
num_cpus = "1.0"
tokio = { version = "0.1.15", features = ["async-await-preview"] }
tokio-codec = "0.1.0"
thruster-core = { path = "../thruster-core" }
thruster-app = { path = "../thruster-app" }
