[package]
name = "middleware-proc"
version = "0.1.0"
authors = ["Pete Mertz <peter.s.mertz@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.15.27", features = ["full"] }
quote = "0.6.3"
