[package]
name = "thruster-middleware"
version = "0.1.0"
authors = ["Pete Mertz <peter.s.mertz@gmail.com>"]
description = "A middleware based http async web server."
readme = "README.md"
license = "MIT"
documentation = "https://thruster.github.com"
homepage = "https://thruster.github.com"
repository = "https://github.com/trezm/thruster"
edition = "2018"

[features]
# default = []
default = ["hyper_server"]
hyper_server = ["hyper"]

[dependencies]
futures-legacy = { version = "0.1.23", package = "futures" }
futures-preview = "0.3.0-alpha.13"
hyper = { version = "0.12.25", optional = true }
net2 = "0.2"
num_cpus = "1.0"
tokio = { version = "0.1.15", features = ["async-await-preview"] }
tokio-codec = "0.1.0"
thruster-core = { path = "../thruster-core" }
